# Generated by Django 2.1.5 on 2019-01-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('dep', models.CharField(max_length=100)),
                ('det_time', models.DateTimeField()),
                ('to', models.CharField(max_length=100)),
                ('pax', models.IntegerField(default=1)),
                ('car', models.CharField(max_length=20)),
            ],
        ),
    ]
