# Generated by Django 2.1.5 on 2019-01-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(choices=[('OW', 'Oneway'), ('RT', 'Roundtrip')], default='OW', max_length=2)),
                ('your_choice', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='result',
            old_name='dep',
            new_name='dep_city',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='arr',
            new_name='resort',
        ),
        migrations.AddField(
            model_name='result',
            name='boots',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
