# Generated by Django 2.1.5 on 2019-01-23 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offer',
            new_name='Result',
        ),
    ]
