# Generated by Django 2.1.5 on 2019-01-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/avatar_pics/default.jpg', upload_to='avatar_pics'),
        ),
    ]
