# Generated by Django 2.1.5 on 2019-01-20 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_offer_det_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_car', models.CharField(max_length=20)),
                ('your_model', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='offer',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='polls.Car'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pax',
            field=models.IntegerField(default=3),
        ),
    ]
