# Generated by Django 2.1.5 on 2019-01-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190123_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='to',
            new_name='arr',
        ),
        migrations.AddField(
            model_name='result',
            name='baggage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='comment',
            field=models.TextField(default=None, max_length=300),
        ),
    ]
