# Generated by Django 2.1.5 on 2019-02-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190204_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='your_model',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
