# Generated by Django 2.1.5 on 2019-02-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190201_1226'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TripType',
        ),
    ]
