# Generated by Django 2.1.5 on 2019-02-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_result_pax_reserved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='pax',
        ),
        migrations.RemoveField(
            model_name='result',
            name='pax_reserved',
        ),
        migrations.AddField(
            model_name='result',
            name='passengers',
            field=models.ManyToManyField(blank=True, null=True, to='polls.Profile'),
        ),
        migrations.AddField(
            model_name='result',
            name='seats',
            field=models.IntegerField(default=1),
        ),
    ]
