# Generated by Django 2.1.5 on 2019-02-01 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_result_pax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='time',
        ),
        migrations.AddField(
            model_name='result',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='result',
            name='dep_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='result',
            name='pax',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='result',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
