# Generated by Django 2.1.5 on 2019-02-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190209_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='passengers',
            field=models.ManyToManyField(blank=True, to='polls.Profile'),
        ),
    ]
