# Generated by Django 2.1.5 on 2019-02-01 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190201_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='arr_adress',
            new_name='arr_address',
        ),
        migrations.RenameField(
            model_name='result',
            old_name='dep_adress',
            new_name='dep_address',
        ),
    ]
