# Generated by Django 2.1.5 on 2019-02-13 07:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20190213_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='dep_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='result',
            name='passengers',
            field=models.ManyToManyField(blank=True, null=True, to='polls.Profile'),
        ),
    ]
