# Generated by Django 2.1.5 on 2019-02-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20190213_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='dep_date',
            field=models.DateTimeField(),
        ),
    ]
