# Generated by Django 2.1.5 on 2019-02-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20190214_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='arr_address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='result',
            name='dep_address',
            field=models.CharField(max_length=300),
        ),
    ]
