# Generated by Django 2.1.5 on 2019-02-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20190216_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='passengers',
            field=models.ManyToManyField(blank=True, to='polls.Profile'),
        ),
    ]
