# Generated by Django 2.1.5 on 2019-02-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20190216_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='result',
            options={'ordering': ['-created_date']},
        ),
    ]
