# Generated by Django 2.1.5 on 2019-02-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20190225_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='title',
            field=models.CharField(help_text='Say a coule of words to attract attention', max_length=100),
        ),
    ]
