# Generated by Django 2.1.5 on 2019-02-25 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20190225_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='your_model',
            new_name='car_color',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='your_car',
            new_name='car_model',
        ),
        migrations.AddField(
            model_name='result',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Car'),
        ),
    ]
