# Generated by Django 2.1.5 on 2019-02-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20190226_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='comment',
            field=models.CharField(blank=True, help_text='Any additional info that you consider important', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='dep_address',
            field=models.CharField(help_text='City or district', max_length=300),
        ),
    ]
