# Generated by Django 2.1.5 on 2019-02-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20190226_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='seats',
            field=models.IntegerField(),
        ),
    ]
