# Generated by Django 2.1.5 on 2019-02-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20190226_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='dep_date',
            field=models.DateTimeField(),
        ),
    ]
