# Generated by Django 2.1.5 on 2019-02-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20190226_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='dep_date',
            field=models.DateField(),
        ),
    ]
