# Generated by Django 2.1.5 on 2019-03-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0023_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
