# Generated by Django 2.1.5 on 2019-07-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_auto_20190723_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='car',
        ),
        migrations.AddField(
            model_name='result',
            name='car',
            field=models.ManyToManyField(blank=True, null=True, to='polls.Car'),
        ),
    ]
